---
title: "Microbiol612"
author: "Corine Jackman"
date: "March 18, 2016"
output: html_document
---
#In order to become familiar with R, we used Gapminder which contained the country,the year, population, continent, life expecancy, and GDP per capita. The data #was saved to myprojects and  was uploaded during class using the following 2 lines of code. The term "gapminder" have the table as an output.

getwd()
gapminder<-read.table("./r-novice-gapminder-files/data/gapminder-FiveYearData.csv", sep=',', header=T)
gapminder

#The question was, using gapminder data, manipulate the list to specify the life expectancies and corresponding years of American countries only. Then, plot the life expectancies of  American countries between the 1950's to the present. In order to do this, dplyr package was installed and loaded using the following code.

install.packages('dplyr')
library(dplyr)

#Then, using pipes, the filter and select functions, gapminder was manipulated to show american countries with corresponding year and life expectancies. 

year_country_life_ <- gapminder %>% select(year,continent,country,lifeExp)

year_country_life_Americas <- gapminder %>% 
filter(continent=="Americas") %>%
select(year,country,lifeExp)

year_country_life_Americas

#In order to plot this data, ggplot was installed by clicking packages and clicking "ggplot2". Then the following code showed the x axis, y axis and title as "year", "Life Expectancy" and "Life Expectancy in American Countries", respectively. The "color=country" designates a color to each country and geom_point() shows each data entry as an individual point on the plot.

ggplot(data = year_country_life_Americas, aes(x = year, y = lifeExp, color=country)) +ggtitle("Life Expectancy in American Countries") +
  geom_point()
  
